# Generated by Django 5.1.1 on 2024-10-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
