# Generated by Django 5.1.1 on 2024-10-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_comentario_noticia_comentario_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='armazenamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celular',
            name='bateria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celular',
            name='camera',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='celular',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='celular',
            name='memoria_ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celular',
            name='modelo_bateria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='celular',
            name='processador',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='celular',
            name='resolucao_tela',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='celular',
            name='tamanho_tela',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='celular',
            name='tipo_conexao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='celular',
            name='velocidade_clock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='celular',
            name='velocidade_processador',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='celular',
            name='fabricante',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='celular',
            name='link_venda',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='celular',
            name='modelo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='celular',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
