# Generated by Django 5.1.1 on 2024-10-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_celular_armazenamento_celular_bateria_celular_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='imagem_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
