# Generated by Django 5.1.1 on 2024-11-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_celular_imagem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem_link',
            field=models.URLField(blank=True, max_length=999, null=True),
        ),
    ]
